### ISSUE TITLE
ability to set publish timeout

### ISSUE THREAD

**Issue by jkarneges** [fanout/ruby-pubcontrol#3]
It should be possible to set the maximum time to spend attempting to make a publish call, so that calls don't get stuck due to networking issues or other reasons.

According to the [docs](http://ruby-doc.org/stdlib-1.9.3/libdoc/net/http/rdoc/Net/HTTP.html) there are a bunch of timeout related parameters we can set: `continue_timeout`, `open_timeout`, `read_timeout`, and `ssl_timeout`. None of these parameters appear to cover write timeouts, so we may need to change HTTP libraries or find some alternative way to abort a request. Maybe consider setting low level socket timeout options.

**Comment by JohanBengtsson** [comment]
@jkarneges Hey there, any plans on addressing this issue you think? We're using Ruby 2.4.1

**Comment by jkarneges** [comment]
We investigated this issue and made a fix. It's not perfect but hopefully in practice it won't be a real problem.

Basically, Ruby Net::HTTP timeouts are a bit limited:

* Can't set a write timeout: https://bugs.ruby-lang.org/issues/13396
* Read timeout can be set, but it's the time between reads. There doesn't seem to be a way to set a timeout on the whole transaction.
* net-http-persistent doesn't allow setting `continue_timeout` or `ssl_timeout`. Hopefully these have sane defaults and changing them is not important.

Our fix sets `open_timeout` and `read_timeout` to 10 seconds. As long as your TCP send buffer is larger than the POST body, then you shouldn't get a blocking write, and the lack of a write timeout won't matter. On Linux, the TCP send buffer size appears to be controlled by sysctl settings `net.core.wmem_default`, `net.core.wmem_max`, and `net.ipv4.tcp_wmem` (in tests on my Linux machine, the buffer size for a non-localhost connection seemed to be around 200k which is what `net.core.wmem_max` was set to). Since the response to a publish API call is just the word "Published", it is unlikely the data will fragment and reset the read timeout. So I think all will be well as long as you don't POST larger than your TCP send buffer.

An updated gem will be published shortly.

**Comment by kbokarius** [comment]
Published pubcontrol-1.2.2 gem.

**Comment by JohanBengtsson** [comment]
@jkarneges @kbokarius thanks! we will try this out beginning of next week :)
